spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
logging:
  level:
    root: INFO
    kr.hhplus.be.server: INFO
